site_name: Slackoff
site_description: Automatically sign out of Slack workspaces on macOS.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/slackoff
edit_uri: https://github.com/jacebrowning/slackoff/edit/main/docs

theme: readthedocs

nav:
  - Home: index.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
