site_name: slackoff
site_description: Automate Slack workspaces.
site_author: Jace Browning

repo_url: https://github.com/jacebrowning/slackoff
edit_uri: https://github.com/jacebrowning/slackoff/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
